import {
    AddIcon,
    ArrowForwardIcon,
    CheckIcon,
    CloseIcon,
    CopyIcon,
    DeleteIcon,
    ExternalLinkIcon,
    HamburgerIcon,
    MoonIcon,
    RepeatIcon,
    SearchIcon,
    SettingsIcon,
    SunIcon,
    TimeIcon
} from '@chakra-ui/icons';

import { BsDot } from 'react-icons/bs';
import {
    FaBoxOpen,
    FaCalendar,
    FaCalendarPlus,
    FaCodeBranch,
    FaCubes,
    FaMinusCircle,
    FaPlay,
    FaPrint,
    FaSave,
    FaSitemap,
    FaSortNumericDown,
    FaStop,
    FaTable,
    FaTachometerAlt,
    FaToggleOn,
    FaUser,
    FaUserCog,
    FaUserPlus,
    FaUsers,
    FaWrench
} from 'react-icons/fa';
import { FaBarsProgress, FaFaceSmile, FaNoteSticky, FaPencil, FaTableCellsLarge, FaTableList } from 'react-icons/fa6';

const iconSet = {
    wrench: FaWrench,
    play: FaPlay,
    x: CloseIcon,
    check: CheckIcon,
    printer: FaPrint,
    queue: FaSortNumericDown,
    calendar: FaCalendar,
    calendarAdd: FaCalendarPlus,
    search: SearchIcon,
    settings: SettingsIcon,
    dashboard: FaTachometerAlt,
    add: AddIcon,
    table: FaTable,
    pencil: FaPencil,
    smile: FaFaceSmile,
    site: FaSitemap,
    toggles: FaToggleOn,
    note: FaNoteSticky,
    stop: FaStop,
    moon: MoonIcon,
    sun: SunIcon,
    external: ExternalLinkIcon,
    delete: DeleteIcon,
    save: FaSave,
    person: FaUser,
    people: FaUsers,
    personPlus: FaUserPlus,
    copy: CopyIcon,
    peerInstructor: FaUserCog,
    clock: TimeIcon,
    material: FaCubes,
    materialAmount: FaBarsProgress,
    refresh: RepeatIcon,
    branch: FaCodeBranch,
    rightArrow: ArrowForwardIcon,
    dot: BsDot,
    list: FaTableList,
    grid: FaTableCellsLarge,
    minus: FaMinusCircle,
    hamburger: HamburgerIcon,
    boxes: FaBoxOpen
};

export default iconSet;
