import { ObjectId } from 'mongodb';

import clientPromise from '@/lib/mongodb';
import dayjs from '@/lib/time';

import { PrintStates } from '@/util/states';

export default async function handler(req, res) {
    const mongoClient = await clientPromise;

    const body = req.body;

    if (req.method === 'PUT') {
        const linkedPrintId = body.id;
        const action = body.action;

        // try converting the id to an object id to see if the id is a mognodb id or a printer job id
        let objectId;
        try {
            objectId = new ObjectId(linkedPrintId);
        } catch (e) {
            objectId = null;
        }

        const print = await mongoClient
            .db('printing')
            .collection('print-log')
            .findOne({
                $or: [{ linkedPrintId: linkedPrintId }, { _id: objectId || '' }]
            });

        // if the print isnt found tell andrew to link it
        if (!print) {
            res.status(400).json({
                success: false,
                type: 'nolink',
                message: 'Print not linked'
            });
            return;
        }

        if (print.state === action) {
            res.status(400).json({
                success: false,
                type: 'duplicateevent',
                message: "Print's latest event is the same as the requested action"
            });
        }

        const timestamp = dayjs.utc(body?.timestamp).toISOString() || dayjs().utc().toISOString();

        // 1 = start print
        if (action === PrintStates.PRINTING) {
            // check if a print is running on the printer
            const runningPrint = await mongoClient.db('printing').collection('print-log').findOne({
                printer: print.printer,
                state: PrintStates.PRINTING
            });

            if (runningPrint) {
                res.status(400).json({
                    success: false,
                    type: 'printerbusy',
                    message: 'Printer still running a print',
                    printId: runningPrint?.linkedPrintId || runningPrint._id.toString()
                });
                return;
            }

            // update the print state to printing
            const data = await mongoClient
                .db('printing')
                .collection('print-log')
                .findOneAndUpdate(
                    {
                        _id: print._id
                    },
                    {
                        $set: {
                            state: PrintStates.PRINTING,
                            updatedAt: dayjs().utc().toISOString()
                        },
                        $push: {
                            events: {
                                type: PrintStates.PRINTING,
                                timestamp: timestamp,
                                notes: '[AUTOGENERATED EVENT]'
                            }
                        }
                    }
                );

            // update printer
            const printer = await mongoClient
                .db('printing')
                .collection('printers')
                .findOneAndUpdate(
                    {
                        id: print.printer
                    },
                    {
                        $set: {
                            currentTray: print._id.toString(),
                            updatedAt: dayjs().utc().toISOString()
                        }
                    }
                );

            res.status(200).json({
                success: true
            });
        } else if (action === PrintStates.COMPLETED) {
            // check if this print is running on the printer
            const printerPre = await mongoClient.db('printing').collection('printers').findOne({
                id: print.printer
            });

            if (printerPre.currentTray !== print._id.toString()) {
                res.status(400).json({
                    success: false,
                    type: 'notrunning',
                    message: 'Print not found running on its expected printer'
                });
                return;
            }

            // update the print state to completed and add event
            const data = await mongoClient
                .db('printing')
                .collection('print-log')
                .findOneAndUpdate(
                    {
                        _id: print._id
                    },
                    {
                        $set: {
                            state: PrintStates.COMPLETED,
                            updatedAt: dayjs().utc().toISOString()
                        },
                        $push: {
                            events: {
                                type: PrintStates.COMPLETED,
                                timestamp: timestamp,
                                notes: '[AUTOGENERATED EVENT]'
                            }
                        }
                    }
                );

            // update printer and pull print from queue
            const printerPost = await mongoClient
                .db('printing')
                .collection('printers')
                .findOneAndUpdate(
                    {
                        id: print.printer
                    },
                    {
                        $pull: {
                            queue: print._id.toString()
                        },
                        $set: {
                            updatedAt: dayjs().utc().toISOString()
                        }
                    }
                );

            res.status(200).json({
                success: true
            });
        } else if (action === PrintStates.FAILED) {
            // check if this print is running on the printer
            const printerPre = await mongoClient.db('printing').collection('printers').findOne({
                id: print.printer
            });

            if (printerPre.currentTray !== print._id.toString()) {
                res.status(400).json({
                    success: false,
                    type: 'notrunning',
                    message: 'Print not found running on its expected printer'
                });
                return;
            }

            // update the print state to completed and add event
            const data = await mongoClient
                .db('printing')
                .collection('print-log')
                .findOneAndUpdate(
                    {
                        _id: print._id
                    },
                    {
                        $set: {
                            state: PrintStates.FAILED,
                            updatedAt: dayjs().utc().toISOString()
                        },
                        $push: {
                            events: {
                                type: PrintStates.FAILED,
                                timestamp: timestamp,
                                notes: '[AUTOGENERATED EVENT]'
                            }
                        }
                    }
                );

            res.status(200).json({
                success: true
            });
        } else {
            res.status(400).json({
                success: false,
                type: 'invalidaction',
                message: 'Invalid action'
            });
        }
    }
}
